name: Deploy Landing Page

on:
  push:
    branches:
      - dev
      # - master

jobs:
  build_and_deploy:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup pnpm environment
        run: |
          pnpm setup
          echo "PNPM_HOME=$HOME/.local/share/pnpm" >> $GITHUB_ENV
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js project
        run: pnpm run build

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project $FIREBASE_PROJECT
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
